# Generated by Django 5.1 on 2024-08-22 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_video_video_file_alter_video_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_watch_time', models.PositiveIntegerField(default=0)),
                ('most_played_section', models.CharField(blank=True, max_length=255, null=True)),
                ('skipped_sections', models.TextField(blank=True, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='streaming.video')),
            ],
        ),
    ]
